import { pgTable, text, serial, timestamp, integer, boolean } from 'drizzle-orm/pg-core';

export const users = pgTable('users', {
  id: serial('id').primaryKey(),
  uid: text('uid').notNull().unique(),
  email: text('email').notNull(),
  createdAt: timestamp('created_at').defaultNow(),
});

export const assets = pgTable('assets', {
  id: serial('id').primaryKey(),
  assetId: text('asset_id').notNull().unique(),
  name: text('name'),
  subsidiary: text('subsidiary'),
  category: text('category'),
  date: text('date'),
  val: text('val'),
  condition: text('condition'),
  conditionLevel: text('condition_level'),
  status: text('status'),
  statusLevel: text('status_level'),
  assetBook: text('asset_book'),
  serialNumber: text('serial_number'),
  assetType: text('asset_type'),
  prorateConvention: text('prorate_convention'),
  assetUnits: integer('asset_units').default(1),
  categorySegment1: text('category_segment_1'),
  categorySegment2: text('category_segment_2'),
  categorySegment3: text('category_segment_3'),
  keySegment1: text('key_segment_1'),
  keySegment2: text('key_segment_2'),
  keySegment3: text('key_segment_3'),
  amortizationStartDate: text('amortization_start_date'),
  depreciationMethod: text('depreciation_method'),
  lifeInMonths: integer('life_in_months'),
  costClearingAccount1: text('cost_clearing_account_1'),
  costClearingAccount2: text('cost_clearing_account_2'),
  costClearingAccount3: text('cost_clearing_account_3'),
  costClearingAccount4: text('cost_clearing_account_4'),
  costClearingAccount5: text('cost_clearing_account_5'),
  costClearingAccount6: text('cost_clearing_account_6'),
  costClearingAccount7: text('cost_clearing_account_7'),
  costClearingAccount8: text('cost_clearing_account_8'),
  listed: text('listed'),
  listedStatus: text('listed_status'),
  assetNumber: text('asset_number'),
  assetDescription: text('asset_description'),
  assetCost: text('asset_cost'),
  datePlacedInService: text('date_placed_in_service'),
  lastUpdated: timestamp('last_updated').defaultNow(),
});

export const maintenance = pgTable('maintenance', {
  id: serial('id').primaryKey(),
  maintenanceId: text('maintenance_id').notNull().unique(), // Firestore document ID
  assetId: text('asset_id'),
  sub: text('sub'),
  type: text('type'),
  date: text('date'),
  cost: text('cost'),
  estimatedCost: text('estimated_cost'),
  actualCost: text('actual_cost'),
  status: text('status'),
  createdAt: timestamp('created_at').defaultNow(),
});
